FROM python:3.14-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock README.md alembic.ini ./
COPY src ./src
COPY alembic ./alembic

RUN uv sync --frozen --no-dev

CMD sh -c "uv run alembic upgrade head && uv run uvicorn src.later_api.main:app --host 0.0.0.0 --port $PORT"
