FROM python:3.13-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock README.md ./
COPY src ./src

RUN uv sync --frozen --no-dev


CMD ["uv", "run", "fastapi", "run", "src/later_api/main.py", "--host", "0.0.0.0", "--port", "$PORT"]
